# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50fde685507ac23ad1dcb936bb8346a47757ecd06928ae1a786f0ca88be6b18a7a95f408683f8e01a1267bf65abd4946af9b779ddb53a42a380cb1a3b79d0de3

test:
  secret_key_base: 2efb685760d270eba6f34d8c847db4764f483c965146fce349355955320d453086929b3ee27dabed7335cf537bbcc867765441234bfef73637ec4d25c3c5c0f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
